

# This file was *autogenerated* from the file diag_bil.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
D = matrix(QQ, [[-_sage_const_1 ,-_sage_const_1 ], [-_sage_const_1 ,_sage_const_0 ]])
A = copy(D)
T = matrix.identity(QQ, _sage_const_2 )

for i in reversed(range(_sage_const_1 , D.nrows())):
    D[i-_sage_const_1 ,:] += D[i,:]
    T[i-_sage_const_1 ,:] += T[i,:]

for i in range(D.nrows()):
    for j in range(i + _sage_const_1 , D.ncols()):
        a = D[j][i] / D[i][i]
        D[j,:] -= a * D[i,:]
        T[j,:] -= a * T[i,:]

        b = D[i][j] / D[i][i]
        D[:,j] -= b * D[:,i]
        T[:,j] -= b * T[:,i]

T = T.transpose()

print(D)
print(T)

print(T.transpose() * A * T)

