

# This file was *autogenerated* from the file cuts_to_qform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_3 = Integer(3); _sage_const_5 = Integer(5)
import qform

cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 ]), vector([_sage_const_0 , _sage_const_1 , -_sage_const_1 , _sage_const_2 ])],
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 ])]
]

B = qform.intersection_form(_sage_const_2 , qform.intersection_data(_sage_const_2 , cuts))
print(B)
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))
print()

cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_2 , _sage_const_0 , _sage_const_1 ]), vector([_sage_const_0 , _sage_const_1 , -_sage_const_1 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_1 ])]
]

B = qform.intersection_form(_sage_const_2 , qform.intersection_data(_sage_const_2 , cuts))
print(B)
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))


cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_2 , _sage_const_1 , _sage_const_2 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_3 , _sage_const_2 , _sage_const_1 , _sage_const_1 ]), vector([_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 ])]
]

B = qform.intersection_form(_sage_const_2 , qform.intersection_data(_sage_const_2 , cuts))
print(B)
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))


cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_3 , _sage_const_2 , _sage_const_3 , _sage_const_2 ]), vector([_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_2 , _sage_const_3 , _sage_const_5 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_1 , _sage_const_2 ])]
]


B = qform.intersection_form(_sage_const_2 , qform.intersection_data(_sage_const_2 , cuts))
print(B)
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))

cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_3 , _sage_const_2 , _sage_const_3 , _sage_const_2 ]), vector([_sage_const_1 , _sage_const_1 , _sage_const_1 , _sage_const_1 ])],
    [vector([_sage_const_3 , _sage_const_2 , _sage_const_1 , _sage_const_1 ]), vector([_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 ])]
]


B = qform.intersection_form(_sage_const_2 , qform.intersection_data(_sage_const_2 , cuts))
print(B)
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))

