

# This file was *autogenerated* from the file qform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_8 = Integer(8); _sage_const_3 = Integer(3); _sage_const_100 = Integer(100); _sage_const_50 = Integer(50)
from functools import reduce
import numpy as np
import random

ESM_dict = {}

def _J(g):
    return block_matrix([[_sage_const_0 , matrix.identity(g)],[-matrix.identity(g), _sage_const_0 ]])

def _Sp(n):
    return Sp(n, ZZ, invariant_form=_J(ZZ(n / _sage_const_2 )))

def _ind(y, x, l, n):
    return l - (n - y - _sage_const_1 ) * (n - y) / _sage_const_2  + x - y - _sage_const_1 

def _count(n):
    return n * (n + _sage_const_1 ) / _sage_const_2 

def _uncount(l):
    # Turns out this is the right expression o.O
    return (-_sage_const_1  + sqrt(_sage_const_1  + _sage_const_8  * float(l))) / _sage_const_2 

def _build_intersection_matrix(g, mats):
    # Generate our base intersection matrix
    blocks = []
    n = int(_uncount(len(mats))) + _sage_const_1 

    for i in range(n):
        blocks.append([])
        for j in range(n):
            if i == j:
                blocks[i].append(matrix(g))
            elif i > j:
                blocks[i].append(-mats[_ind(j, i, len(mats), n)].transpose())
            else:
                blocks[i].append(mats[_ind(i, j, len(mats), n)])

    base_blocks = []

    for i in range(_sage_const_2 ):
        base_blocks.append([])
        for j in range(_sage_const_2 ):
            base_blocks[i].append(blocks[i][j])

    I = block_matrix(blocks)
    B = block_matrix(base_blocks)

    #print(f'Intersection matrix:\n{I}\n')

    assert I.is_skew_symmetric(), "Intersection matrix is not skew-symmetric"

    #print(f'{A}\n')

    return (blocks,I,n,B)

def _all_integers(v):
    return all(list(map(lambda x: x.is_integer(), v)))

def _build_kernel_generators(g, blocks, B, n):
    # Build the kernel of our map
    ker = np.zeros((g * (n - _sage_const_2 ), g * n))

    for i in range(_sage_const_2 , n):
        for j in range(g):
            coeffs = B.inverse() * vector(QQ, [blocks[i][k][j][l]
                for k in range(_sage_const_2 ) for l in range(g)])
            a = _sage_const_1  if _all_integers(coeffs) else _sage_const_1  / reduce(gcd, coeffs) 
            coeffs = a * coeffs

            assert _all_integers(coeffs), \
                    "Kernel generators cannot be given in integer coefficients"

            e = g * (i - _sage_const_2 ) + j
            ker[e,:g * _sage_const_2 ] = coeffs
            ker[e,e + g * _sage_const_2 ] = a
            ker[e] = list(map(int, ker[e]))

    return ker

def _compute_q_form(I, ker):
    # Compute the intersection form
    Q = matrix(len(ker))

    for i,e1 in enumerate(ker):
        for j,e2 in enumerate(ker):
            s = _sage_const_0 
            for k in range(len(e1)):
                for l in range(k + _sage_const_1 , len(e2)):
                    s += (e1[k] * e2[l]) * I[k][l]
            Q[i,j] = s


    assert Q.is_symmetric(), \
            "Intersection form is not symmetric, this likely means the kernel "\
            "was generated incorrectly"

    return Q

def intersection_data(g, cuts):
    """
    Given some elements of (?), find the intersection data using
    basis B.
    :param T: Basis of Lagrangian decomposition in the form of a symplectic
    matrix
    :param B: Initial Lagrangian decomposition, by default this is the 4x4
    identity matrix
    :param M: The (symplectic) intersection pairing for the given basis, by
    default this is J
    :return: A block matrix of intersection data
    """
    J = _J(g)
    I = matrix(len(cuts) * _sage_const_2 )

    for i in range(I.nrows()):
        for j in range(I.ncols()):
            I[i,j] = (matrix(cuts[i//g][i%g]) * J * cuts[j//g][j%g])[_sage_const_0 ]
    
    mats = [I[i:i+g,j:j+g]
            for i in range(_sage_const_0 , I.nrows() - g, g)
            for j in range(i + g, I.ncols(), g)]
    
    return mats

def intersection_form(g, mats):
    """
    Solve for the intersection form given a multisection
    :param int g: Genus of the multisection diagram
    :param list[list[int]] mats: Blocks of the intersection matrix, in the \
            form e.g. (a, b), (a, c), (b, c) where (a, b) looks like \
             [[<a_1, b_1>, ..., <a_1, b_g>],
              [     ⁞    ,  ⋱ ,     ⁞     ],
              [<a_g, b_1>, ..., <a_g, b_g>]]
    :return: Returns the intersection form
    """
    mats = list(map(matrix, mats))

    # Standard assertions
    assert g >= _sage_const_0 , "Genus must be >= 0"
    for i,mat in enumerate(mats):
        assert mat.ncols() == mat.nrows() == g, \
                f"The block\n{mat}\nshould be {g}x{g}, but is actually " \
                f"{mat.nrows()}x{mat.ncols()}"
    assert _uncount(len(mats)).is_integer(), \
            "Intersection blocks don't fit into skew-symmetric matrix"

    blocks,I,n,B = _build_intersection_matrix(g, mats)
    print(I)
    #print(f'Intersection matrix:\n{I}\n')
    ker = _build_kernel_generators(g, blocks, B, n)
    print(ker)
    #print(f'Kernel generators:\n{matrix(ZZ, ker)}\n')

    return _compute_q_form(I, ker)

def signature(B):
    """
    Find the signature of a bilinear form given its matrix representation.
    :param matrix: Matrix representation of a bilinear form B
    :return: Returns the signature of B
    """
    Q = QuadraticForm(ZZ, B + B.transpose())
    return Q.signature_vector()

def definiteness(B):
    Q = QuadraticForm(ZZ, B + B.transpose())
    return Q.compute_definiteness_string_by_determinants()

def parity(B):
    Q = QuadraticForm(ZZ, B + B.transpose())
    return Q.parity()

def _ESMs(g):
    global ESM_dict

    # Memoize the generators of Sp(2g, Z)
    if g in ESM_dict:
        return ESM_dict[g]
    
    ESMs = []
    I2g = matrix.identity(_sage_const_2  * g)
    X = matrix.identity(_sage_const_2  * g)
    for i in range(_sage_const_1 , _sage_const_2  * g - _sage_const_1 , _sage_const_2 ):
        X.swap_rows(i, i + _sage_const_1 )

    def e(i, j):
        E = matrix(_sage_const_2  * g)
        E[i,j] = _sage_const_1 
        return E

    # Element of S_2g transposing 2i and 2i - 1 for all 1 <= i <= g
    def sigma(i):
        return i + _sage_const_1  if i % _sage_const_2  == _sage_const_0  else i - _sage_const_1 

    for i in range(_sage_const_2  * g):
        for j in range(_sage_const_2  * g):
            if i == j:
                continue
            if i == sigma(j):
                ESM = I2g + e(i, j)
            else:
                ESM = I2g + e(i, j) - (-_sage_const_1 )**(i + j) * e(sigma(j), sigma(i))

            ESMs.append(X.transpose() * ESM * X)
            #assert ESMs[-1] in _Sp(2 * g), f"ESM not in Sp({2 * g}, Z)"

    ESM_dict[g] = ESMs
    return ESMs

def random_symplectic_matrix(g, p):
    # transvection = matrix([[1,0,0,0],[0,1,0,0],[1,0,1,0],[0,0,0,1]])
    # rotation     = matrix([[0,0,-1,0],[0,1,0,0],[1,0,0,0],[0,0,0,1]])
    # mix          = matrix([[1,0,0,0],[0,1,0,0],[0,-1,1,0],[-1,0,0,1]])
    # swap         = matrix([[0,1,0,0],[1,0,0,0],[0,0,0,1],[0,0,1,0]])
    # K = matrix([[1,0,0,0],[1,-1,0,0],[0,0,1,1],[0,0,0,-1]])
    # L = matrix([[0,0,-1,0],[0,0,0,-1],[1,0,1,0],[0,1,0,0]])

    ESMs = _ESMs(g)
    P = [random.choice(ESMs) for _ in range(random.randint(_sage_const_1 , p))]
    M = reduce(lambda a, x: a * x, P)

    assert M in _Sp(_sage_const_2  * g), f"Generated matrix is not in Sp({2 * g}, Z)"

    return (M, P)

def random_unimodular_matrix(n):
    matrix_space = sage.matrix.matrix_space.MatrixSpace(ZZ, n)
    return sage.matrix.constructor.random_unimodular_matrix(matrix_space,
            upper_bound=_sage_const_3 )

def random_diagram(g, n):
    """
    Generate a random genus 2 multisection diagram with n + 2 cut systems,
    the first two being the standard alpha and beta cut systems.
    """
    B = matrix.identity(_sage_const_2  * g)
    B = matrix([[_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 , _sage_const_0 , -_sage_const_1 ], [-_sage_const_1 , _sage_const_0 , -_sage_const_1 , _sage_const_1 ], [_sage_const_0 , -_sage_const_1 , _sage_const_1 , _sage_const_0 ]])

    limit = _sage_const_100 

    while True:
        limit_flag = True
        cuts = [[B.column(i + j) for j in range(g)] for i in range(_sage_const_0 , B.ncols(), g)]

        for _ in range(n - _sage_const_1 ):
            l = _sage_const_0 
            while True and l < limit:
                l += _sage_const_1 
                symp_map = random_symplectic_matrix(g, _sage_const_50 )[_sage_const_0 ]
                image = [symp_map * cuts[-_sage_const_1 ][i] for i in range(g)]
                #det = matrix(cuts[-1] + image).determinant()
                det = intersection_data(g, [cuts[-_sage_const_1 ], image])[_sage_const_0 ].determinant()
                if det == _sage_const_1  or det == -_sage_const_1 :
                    break
            limit_flag = limit_flag and l < limit
            cuts.append(image)

        l = _sage_const_0 
        while True and l < limit:
            l += _sage_const_1 
            symp_map = random_symplectic_matrix(g, _sage_const_50 )[_sage_const_0 ]
            image = [symp_map * cuts[-_sage_const_1 ][i] for i in range(g)]
            # det1 = matrix(cuts[-1] + image).determinant()
            # det2 = matrix(image + cuts[0]).determinant()
            det1 = intersection_data(g, [cuts[-_sage_const_1 ], image])[_sage_const_0 ].determinant()
            det2 = intersection_data(g, [image, cuts[_sage_const_0 ]])[_sage_const_0 ].determinant()

            if (det1 == _sage_const_1  or det1 == -_sage_const_1 ) and (det2 == _sage_const_1  or det2 == -_sage_const_1 ):
                break
        cuts.append(image)

        limit_flag = limit_flag and l < limit
        if limit_flag:
            break

    print(intersection_data(_sage_const_2 , cuts)[_sage_const_0 ])
    return cuts

if __name__ == "__main__":
    mats = [
        [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ]],
        [[_sage_const_1 , _sage_const_0 ], [_sage_const_0 , _sage_const_1 ]],
        [[-_sage_const_1 , _sage_const_0 ], [_sage_const_0 , -_sage_const_1 ]],
    ]

    #intersection_form(2, mats)
    _compute_q_form([], [])

