

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0); _sage_const_1 = Integer(1); _sage_const_9 = Integer(9); _sage_const_2 = Integer(2); _sage_const_10 = Integer(10); _sage_const_5 = Integer(5); _sage_const_20 = Integer(20); _sage_const_4 = Integer(4); _sage_const_32 = Integer(32); _sage_const_21 = Integer(21); _sage_const_68 = Integer(68)
B = matrix([[  _sage_const_0 , -_sage_const_1 ,  _sage_const_0 ,  _sage_const_0 ,  _sage_const_9 ,  _sage_const_0 , -_sage_const_2 ,  _sage_const_0 ],
[ -_sage_const_1 ,  _sage_const_0 ,  _sage_const_1 ,  _sage_const_0 ,-_sage_const_10 ,  _sage_const_2 ,  _sage_const_5 , -_sage_const_1 ],
[  _sage_const_0 ,  _sage_const_1 , -_sage_const_2 ,  _sage_const_0 , _sage_const_20 , -_sage_const_4 ,-_sage_const_10 ,  _sage_const_2 ],
[  _sage_const_0 ,  _sage_const_0 ,  _sage_const_0 ,  _sage_const_0 ,  _sage_const_9 ,  _sage_const_0 , -_sage_const_2 ,  _sage_const_0 ],
[  _sage_const_9 ,-_sage_const_10 , _sage_const_20 ,  _sage_const_9 , _sage_const_32 ,-_sage_const_10 ,-_sage_const_21 ,  _sage_const_5 ],
[  _sage_const_0 ,  _sage_const_2 , -_sage_const_4 ,  _sage_const_0 ,-_sage_const_10 ,  _sage_const_2 ,  _sage_const_5 , -_sage_const_1 ],
[ -_sage_const_2 ,  _sage_const_5 ,-_sage_const_10 , -_sage_const_2 ,-_sage_const_21 ,  _sage_const_5 , _sage_const_68 ,-_sage_const_10 ],
[  _sage_const_0 , -_sage_const_1 ,  _sage_const_2 ,  _sage_const_0 ,  _sage_const_5 , -_sage_const_1 ,-_sage_const_10 ,  _sage_const_2 ]])

E8 = matrix([[_sage_const_2 , -_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
    [-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,-_sage_const_1 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_2 ]])

Q = QuadraticForm(ZZ, B + B.transpose())
Q.compute_definiteness()
Q8 = QuadraticForm(ZZ, E8 + E8.transpose())
Q8.compute_definiteness()

print(f'E8 Definiteness: {Q8.compute_definiteness_string_by_determinants()}')
print(f'E8 Signature: {Q8.signature()}')
#print(f'E8 Parity: {Q8.parity()}')
print(f'Definiteness: {Q.compute_definiteness_string_by_determinants()}')
print(f'Signature: {Q.signature()}')
#print(f'Parity: {Q.parity()}')

