

# This file was *autogenerated* from the file test.sage
from sage.all_cmdline import *   # import sage library

_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_4 = Integer(4); _sage_const_12 = Integer(12); _sage_const_8 = Integer(8); _sage_const_0 = Integer(0); _sage_const_10 = Integer(10); _sage_const_6 = Integer(6); _sage_const_5 = Integer(5); _sage_const_3 = Integer(3); _sage_const_32 = Integer(32); _sage_const_22 = Integer(22); _sage_const_20 = Integer(20); _sage_const_14 = Integer(14); _sage_const_136 = Integer(136); _sage_const_96 = Integer(96); _sage_const_68 = Integer(68); _sage_const_100 = Integer(100); _sage_const_46 = Integer(46)
B = matrix([[   _sage_const_2 ,   _sage_const_1 ,  -_sage_const_4 ,  -_sage_const_2 ,  -_sage_const_2 ,  -_sage_const_1 , -_sage_const_12 ,  -_sage_const_8 ],
[   _sage_const_1 ,   _sage_const_0 ,  -_sage_const_2 ,   _sage_const_0 ,  -_sage_const_1 ,   _sage_const_0 ,  -_sage_const_4 ,  -_sage_const_2 ],
[  -_sage_const_4 ,  -_sage_const_2 ,  _sage_const_10 ,   _sage_const_6 ,   _sage_const_5 ,   _sage_const_3 ,  _sage_const_32 ,  _sage_const_22 ],
[  -_sage_const_2 ,   _sage_const_0 ,   _sage_const_6 ,   _sage_const_4 ,   _sage_const_3 ,   _sage_const_2 ,  _sage_const_20 ,  _sage_const_14 ],
[  -_sage_const_2 ,  -_sage_const_1 ,   _sage_const_5 ,   _sage_const_3 , -_sage_const_20 , -_sage_const_14 ,-_sage_const_136 , -_sage_const_96 ],
[  -_sage_const_1 ,   _sage_const_0 ,   _sage_const_3 ,   _sage_const_2 , -_sage_const_14 , -_sage_const_10 , -_sage_const_96 , -_sage_const_68 ],
[ -_sage_const_12 ,  -_sage_const_4 ,  _sage_const_32 ,  _sage_const_20 ,-_sage_const_136 , -_sage_const_96 , _sage_const_100 ,  _sage_const_68 ],
[  -_sage_const_8 ,  -_sage_const_2 ,  _sage_const_22 ,  _sage_const_14 , -_sage_const_96 , -_sage_const_68 ,  _sage_const_68 ,  _sage_const_46 ]])

E8 = matrix([[_sage_const_2 , -_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_0 ],
    [-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ,-_sage_const_1 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,-_sage_const_1 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_2 ,_sage_const_0 ],
    [_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,_sage_const_0 ,-_sage_const_1 ,_sage_const_0 ,_sage_const_0 ,_sage_const_2 ]])

Q = QuadraticForm(ZZ, B + B.transpose())
Q.compute_definiteness()
Q8 = QuadraticForm(ZZ, E8 + E8.transpose())
Q8.compute_definiteness()

print(f'E8 Definiteness: {Q8.compute_definiteness_string_by_determinants()}')
print(f'E8 Signature: {Q8.signature_vector()}')
#print(f'E8 Parity: {Q8.parity()}')
print(f'Definiteness: {Q.compute_definiteness_string_by_determinants()}')
print(f'Signature: {Q.signature_vector()}')
#print(f'Parity: {Q.parity()}')

