

# This file was *autogenerated* from the file cuts_to_qform.sage
from sage.all_cmdline import *   # import sage library

_sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_2 = Integer(2)
import qform

cuts = [
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_0 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_1 , _sage_const_0 , _sage_const_0 ])],
    [vector([_sage_const_0 , _sage_const_0 , _sage_const_1 , _sage_const_0 ]), vector([_sage_const_0 , _sage_const_0 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_1 , _sage_const_0 , _sage_const_1 , _sage_const_1 ]), vector([-_sage_const_1 , _sage_const_1 , _sage_const_0 , _sage_const_1 ])],
    [vector([_sage_const_1 , -_sage_const_1 , -_sage_const_1 , -_sage_const_2 ]), vector([_sage_const_2 , -_sage_const_1 , _sage_const_1 , _sage_const_1 ])]
]

print(qform.cuts_to_intersection(_sage_const_2 ,cuts))

B = qform.intersection_form(_sage_const_2 , qform.cuts_to_intersection(_sage_const_2 , cuts))
print(B)
print()
print(qform.signature(B))
print(qform.definiteness(B))
print(qform.parity(B))
print()

